# Default values for event-generator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tango_gateway:
  replicaCount: 1
  enabled: true
  image:
    registry:  nexus.engageska-portugal.pt/ska-docker
    image: tango-example
    tag: latest
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 256Mi
