apiVersion: v2
appVersion: "1.0"
description: A Helm chart for deploying the Tango event generator device on k8s
name: event-generator
version: 0.1.1
dependencies:
- name: tango-base
  version: 0.2.1
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: tango-base.enabled,global.sub-system.tango-base.enabled