apiVersion: v2
appVersion: "1.0"
description: A Helm chart for deploying the Tango event generator device on k8s
name: event-generator
version: 0.2.1
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: tango-base
  version: 0.2.5
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
  condition: tango-base.enabled,global.sub-system.tango-base.enabled
