# Default values for event-generator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000

events_generator:
  replicaCount: 1
  enabled: true
  image:
    registry:  nexus.engageska-portugal.pt/ska-docker
    image: tango-example
    tag: 0.3.4
    pullPolicy: IfNotPresent
  tangoDeviceName: "test/device/1"

labels:
  app: tango-example

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 256Mi
