[tool.poetry]
name = "ska-tango-examples"
version = "0.5.0"
description = "This project demonstrates how to structure an SKA project that provides some simple Tango devices coded in PyTango."
authors = ["Matteo Di Carlo <matteo.dicarlo@inaf.it>"]
license = "BSD 3-Clause"

[[tool.poetry.source]]
name = 'ska-nexus'
url = 'https://nexus.engageska-portugal.pt/repository/pypi/simple'

[tool.poetry.dependencies]
python = "^3.6"
numpy = "^1.19.2"
pytango = "^9.3.3"
jsonschema = "^3.2.0"
ska-tango-base = "^0.11.2"
ska-ser-logging = "^0.4.0"
ska-ser-log-transactions = "^0.2.1"

[tool.poetry.dev-dependencies]
isort = "^5.6.4"
black = "^20.8b1"
flake8 = "^3.9.2"
pylint-junit = "^0.3.2"
pylint = "^2.8.2"
pytest = "^6.1.2"
pytest-bdd = "^4.0.1"
pytest-cov = "^2.12.1"
pytest-forked = "^1.3.0"
pytest-json-report = "^1.4.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
