[tool.poetry]
name = "ska-tango-examples"
version = "0.4.19"
description = "SKA Tango Examples"
authors = ["Matteo Di Carlo <tmatteo.dicarlo@inaf.it>"]
license = "BSD-3-Clause"
packages = [
    { include = "ska_tango_examples", from = "src" }
]

[tool.poetry.scripts]
TangoExampleCounterDS = 'ska_tango_examples.counter.Counter:main'
TangoExampleMotorDS = 'ska_tango_examples.basic_example.Motor:main'
TangoExampleEventReceiverDS = 'ska_tango_examples.basic_example.EventReceiver:main'
TangoExampleTabataDS = 'ska_tango_examples.tabata.Tabata:main'
TangoExampleAsyncTabataDS = 'ska_tango_examples.tabata.AsyncTabata:main'

[[tool.poetry.source]]
name = 'ska-nexus'
url = 'https://artefact.skao.int/repository/pypi-internal/simple'

[tool.poetry.dependencies]
python = "^3.7"
jsonschema = "^4.0.1"
pytango = "^9.3.3"
ska-tango-base = "^0.12.0"
ska-ser-logging = "*"
ska-ser-log-transactions = "*"
numpy = "^1.21.0"
debugpy = "^1.5.1"
packaging = "20.9"
six = "1.15.0"
toml = "0.10.2"
appdirs = "1.4.4"
attrs = "^21.4.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pylint = "^2.8.2"
pytest = "^7.1.0"
pytest-bdd = "^4.0.1"
pytest-cov = "^2.10.1"
isort = "^5.6.4"
flake8 = "^3.9.2"
pylint-junit = "^0.3.2"
coverage = "^6.1.1"
pytest-json-report = "^1.4.1"
pytest-forked = "^1.3.0"
pytest-mock = "^3.6.1"
pytest-xdist = "^2.5.0"
pytest-repeat = "^0.9.1"
pytest-timeout = "^2.0.1"
platformdirs = "^2.5.1"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 79

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
