apiVersion: v2
name: ska-tango-examples-test-parent
description: A Helm parent chart for the Tango Example
type: application
version: 0.1.10
appVersion: 0.1.10
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-tango-util
  version: 0.3.7
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-base
  version: 0.3.8
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-examples
  version: 0.4.17
  repository: file://../ska-tango-examples
  alias: tango_example
- name: ska-webjive
  version: 1.0.24
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-webjive.enabled
- name: ska-webjive-auth
  version: 0.1.3
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-webjive.enabled
- name: ska-dashboard-repo
  version: 0.1.7
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-webjive.enabled
