apiVersion: v2
name: ska-tango-examples-test-parent
description: A Helm parent chart for the Tango Example
type: application
version: 0.1.16
appVersion: 0.1.16
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-tango-base
  version: 0.4.16
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-examples
  version: 0.5.0
  repository: file://../ska-tango-examples
- name: ska-tango-taranta
  version: 2.8.3
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-taranta.enabled
- name: ska-tango-taranta-auth
  version: 0.2.2
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-taranta-auth.enabled
- name: ska-dashboard-repo
  version: 0.1.9
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-dashboard-repo.enabled

  # ska-tango-util isn't used directly by this chart. But because Helm named template
  # names are global, the version of ska-tango-util effectively used by all subcharts
  # is the most recent one loaded. So best we can do is pin a version by including this.
- name: ska-tango-util
  version: 0.4.16
  repository: https://artefact.skao.int/repository/helm-internal
