apiVersion: v2
name: ska-tango-examples-test-parent
description: A Helm parent chart for the Tango Example
type: application
version: 0.1.10
appVersion: 0.1.10
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: tango-base
  version: 0.2.23
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: tango-util
  version: 0.2.14
  repository: https://nexus.engageska-portugal.pt/repository/helm-chart
- name: ska-tango-examples
  version: 0.2.12
  repository: file://../ska-tango-examples
  alias: tango_example