display: ":0"
xauthority: "~/.Xauthority"

global:
  labels:
    app: ska-tango-examples
  minikube: true
  operator: true
  tango_host: databaseds-tango-base-test:10000
  sub-system:
    ska-tango-base:
      enabled: false

code-server:
  image:
    repository: registry.gitlab.com/ska-telescope/ska-cicd-k8s-tools/ska-dev-code-server
    tag: '0.8.7-dev.c5d165214'

ska-tango-base:
  databaseds:
    image:
      registry: registry.gitlab.com/ska-telescope/ska-tango-images
      tag: 9.4.1-dev.cf6108963
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false
  itango:
    enabled: true
  jive:
    enabled: false
  deviceServers: []

ska-tango-examples:
  events_generator:
    enabled: false
  deviceServers:
    enabled: true
    servers:
      calendarclock:
        enabled: false
      logtestupstream:
        enabled: false
      logtestdownstream:
        enabled: false
      motor:
        enabled: false
      powersupply:
        enabled: false
      timer:
        enabled: true
      theexample:
        enabled: true
      tabata:
        enabled: true
      eventreceiver:
        enabled: false
      tarantatestdevice:
        enabled: false
      asynctabata:
        enabled: true
      forattrtabata:
        enabled: false
      multidevice:
        enabled: false
      conflictdeployment:
        enabled: false
      conflict:
        enabled: false
      helloworld:
        enabled: false
      slowdevice:
        enabled: false
      incorrectconfiguration:
        enabled: false
      circulardependency:
        enabled: false
      notangohost:
        enabled: false

ska-taranta:
  enabled: false

ska-taranta-auth:
  enabled: false

ska-dashboard-repo:
  enabled: false
