display: ":0"
xauthority: "~/.Xauthority"

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false
  itango:
    enabled: true
  jive:
    enabled: false

tango_example:
  deviceServers:
    theexample:
      instances: ["test"]
      polling: 600