display: ":0"
xauthority: "~/.Xauthority"

global:
  labels:
    app: ska-tango-examples
  minikube: true
  operator: true
  tango_host: databaseds-tango-base-test:10000
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  dsconfig:
    timeout: 300s
    image:
        registry: artefact.skao.int
        image: ska-tango-images-tango-dsconfig
        tag: 1.5.11
        pullPolicy: IfNotPresent
  tangodb:
    use_pv: true
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  itango:
    enabled: true
  jive:
    enabled: false
  deviceServers: []

ska-tango-examples:
  events_generator:
    enabled: false
  deviceServers:
    enabled: true
    servers:
      calendarclock:
        enabled: false
      logtestupstream:
        enabled: false
      logtestdownstream:
        enabled: false
      motor:
        enabled: false
      powersupply:
        enabled: false
      timer:
        enabled: true
      theexample:
        enabled: true
      tabata:
        enabled: true
      eventreceiver:
        enabled: false
      tarantatestdevice:
        enabled: false
      asynctabata:
        enabled: true
      forattrtabata:
        enabled: false
      multidevice:
        enabled: false
      conflictdeployment:
        enabled: false
      conflict:
        enabled: false
      helloworld:
        enabled: false
      slowdevice:
        enabled: false
      incorrectconfiguration:
        enabled: false
      circulardependency:
        enabled: false
      notangohost:
        enabled: false

ska-taranta:
  enabled: false

ska-taranta-auth:
  enabled: false

ska-dashboard-repo:
  enabled: false
