display: ":0"
xauthority: "~/.Xauthority"

global:
  labels:
    app: tango-example
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  sub-system:
    tango-base:
      enabled: false

tango-base:
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false
