display: ":0"
xauthority: "~/.Xauthority"

global:
  labels:
    app: ska-tango-examples
  minikube: true
  operator: true
  tango_host: databaseds-tango-base-test:10000
  sub-system:
    ska-tango-base:
      enabled: false

ska-tango-base:
  dsconfig:
    timeout: 300s
  tangodb:
    use_pv: true
  vnc:
    enabled: false
  tangorest:
    enabled: false
  ingress:
    enabled: false
  itango:
    enabled: true
  jive:
    enabled: false
  deviceServers: []

ska-tango-examples:
  events_generator:
    enabled: false
  deviceServers:
    enabled: true
    servers:
      motor:
        enabled: false
      powersupply:
        enabled: false
      timer:
        enabled: true
      longrunning:
        enabled: true
      theexample:
        enabled: false
      tabata:
        enabled: true
      eventreceiver:
        enabled: true
      tarantatestdevice:
        enabled: false
      asynctabata:
        enabled: true
      forattrtabata:
        enabled: true

ska-taranta:
  enabled: false

ska-taranta-auth:
  enabled: false

ska-dashboard-repo:
  enabled: false
