{{ if .Values.events_generator.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "event-generator.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "event-generator.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "event-generator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ template "event-generator.name" . }}-{{ .Release.Name }}
  replicas: {{ .Values.events_generator.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "event-generator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: event-generator
          image: "{{ .Values.events_generator.image.registry }}/{{ .Values.events_generator.image.image }}:{{ .Values.events_generator.image.tag }}"
          imagePullPolicy: {{ .Values.events_generator.image.pullPolicy }}
          command:
            - sh
          args:
            - -c
            - "/venv/bin/python /app/module_example/TestDevice.py test"
          env:
          - name: TANGO_HOST
            value: {{ .Values.global.tango_host}}
          - name: DEVICE_NAME
            value: {{ .Values.events_generator.tangoDeviceName }}
{{ end }}