apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: event-generator-{{ template "event-generator.name" . }}-{{ .Release.Name }}
  labels: 
{{ include "event-generator.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "event-generator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "event-generator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.image }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
          args:
            - -c
            - "/venv/bin/python /app/module_example/TestDevice.py test"
          volumeMounts:
            - name: tango-test-device
              mountPath: /test-device
          env:
          - name: TANGO_HOST
            value: databaseds-tango-base-{{ .Release.Name }}:10000
          - name: DEVICE_NAME
            value: {{ .Values.tangoDeviceName }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
