# Default values for tango-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

tangodb:
  enabled: true
  pvEnabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-db
    tag: latest
    pullPolicy: IfNotPresent
  db:
    rootpw: secret
    db: tango
    user: tango
    password: tango
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem

databaseds:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-cpp
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 200m     # 200m = 0.2 CPU
      memory: 256Mi # 256Mi = 0.25 GB mem

itango:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-itango
    tag: latest
    pullPolicy: IfNotPresent

tangotest:
  enabled: true
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

jive:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

logviewer:
  enabled: false
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

tangorest:
  enabled: true
  replicas: 3
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: tango-rest
    tag: latest
    pullPolicy: IfNotPresent

# Configure Ingress resource that allow you to access the Tango REST API
ingress:
  enabled: true
  hostname: tango-base.minikube.local

  # Ingress annotations
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/x-forwarded-prefix: true
    nginx.ingress.kubernetes.io/ssl-redirect: false

  # Ingress TLS configuration
  #
  tls:
    enabled: true
    secretname: "tls-secret-tango-base-{{ .Release.Name }}"
    hostname: "{{ .Values.ingress.hostname }}"

nodeSelector: {}

affinity: {}

tolerations: []
