{{ if .Values.jive.enabled }}
---

apiVersion: v1
kind: Pod
metadata:
  name: jive-{{ template "ska-tango-examples.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: jive-{{ template "ska-tango-examples.name" . }}
    chart: {{ template "ska-tango-examples.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  containers:
  - name: jive
    image: "{{ .Values.jive.image.registry }}/{{ .Values.jive.image.image }}:{{ .Values.jive.image.tag }}"
    imagePullPolicy: {{ .Values.jive.image.pullPolicy }}
    command:
      - /usr/local/bin/wait-for-it.sh
      - databaseds-{{ template "ska-tango-examples.name" . }}:10000
      - --timeout=30
      - --strict
      - --
      - /usr/local/bin/jive
    env:
    - name: XAUTHORITY
      value: "/tmp/.Xauthority"
    - name: DISPLAY
      value: "{{ .Values.display }}"
    - name: TANGO_HOST
      value: databaseds-{{ template "ska-tango-examples.name" . }}:10000
    volumeMounts:
      - name: xauthority
        mountPath: /tmp/.Xauthority
        readOnly: true
  volumes:
  - hostPath:
      path: {{ .Values.xauthority }}
      type: File
    name: xauthority
  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}