# Default values for ska-tango-examples.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

tangodb:
  enabled: true
  image:
    registry: ska-registry.av.it.pt/ska-docker
    image: tango-db
    tag: latest
    pullPolicy: IfNotPresent
  db:
    rootpw: secret
    db: tango
    user: tango
    password: tango
  resources:
    requests:
    cpu: 200m     # 200m = 0.2 CPU
    memory: 256Mi # 256Mi = 0.25 GB mem

databaseds:
  enabled: true
  image:
    registry: ska-registry.av.it.pt/ska-docker
    image: tango-cpp
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
    cpu: 200m     # 200m = 0.2 CPU
    memory: 256Mi # 256Mi = 0.25 GB mem

itango:
  enabled: false
  image:
    registry: ska-registry.av.it.pt/ska-docker
    image: tango-itango
    tag: latest
    pullPolicy: IfNotPresent

tangorest:
  enabled: false
  image:
    registry: ska-registry.av.it.pt/ska-docker
    image: tango-rest
    tag: latest
    pullPolicy: IfNotPresent

tangotest:
  enabled: false
  image:
    registry: ska-registry.av.it.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

astor:
  enabled: true
  image:
    registry: ska-registry.av.it.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

starterexample:
  enabled: false
  image:
    registry: ska-registry.av.it.pt/ska-docker
    image: tango-starter
    tag: latest
    pullPolicy: IfNotPresent

jive:
  enabled: false
  image:
    registry: ska-registry.av.it.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

logviewer:
  enabled: false
  image:
    registry: ska-registry.av.it.pt/ska-docker
    image: tango-java
    tag: latest
    pullPolicy: IfNotPresent

pogo:
  enabled: false
  image:
    registry: ska-registry.av.it.pt/ska-docker
    image: tango-pogo
    tag: latest
    pullPolicy: IfNotPresent

tangoexample:
  enabled: true
  debug: false
  debugPort: 32678
  image:
    registry: ska-registry.av.it.pt/tango-example
    image: powersupply
    tag: latest
    pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []
