display: ":0"
xauthority: "~/.Xauthority"
minikube: true

enabled: true

global:
  labels:
    app: ska-docker
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
  tango_host: databaseds-tango-base-test:10000
  environment_variables: []
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent

dsconfig:
  configuration_file: data/configuration.json
  
deviceServers:
  - name: powersupply
    function: tango-example-powersupply
    domain: tango-example
    args:
      - -c
      - "/venv/bin/python /app/module_example/powersupply.py test"
    environment_variables:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ .Release.Name }}:10000
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-example
      tag: latest
      pullPolicy: IfNotPresent

  - name: motor
    function: tango-example-motor
    domain: tango-example
    args:
      - -c
      - "/venv/bin/python /app/module_example/Motor.py test"
    environment_variables:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ .Release.Name }}:10000
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-example
      tag: latest
      pullPolicy: IfNotPresent

  - name: webjivetestdevice
    function: tango-example-webjivetestdevice
    domain: tango-example
    args:
      - -c
      - "/venv/bin/python /app/module_example/WebjiveTestDevice.py test"
    environment_variables:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ .Release.Name }}:10000
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-example
      tag: latest
      pullPolicy: IfNotPresent

  - name: calendarclock
    function: tango-example-calendarclock
    domain: tango-example
    args:
      - -c
      - "/venv/bin/python /app/module_example/CalendarClock.py test"
    environment_variables:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ .Release.Name }}:10000
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-example
      tag: latest
      pullPolicy: IfNotPresent

  - name: eventreceiver
    function: tango-example-eventreceiver
    domain: tango-example
    args:
      - -c
      - "/venv/bin/python /app/module_example/EventReceiver.py test"
    environment_variables:
      - name: TANGO_HOST
        value: databaseds-tango-base-{{ .Release.Name }}:10000
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-example
      tag: latest
      pullPolicy: IfNotPresent

nodeSelector: {}

affinity: {}

tolerations: []
