{{ if .Values.events_generator.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: event-generator-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: event-generator
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: event-generator-{{ .Release.Name }}
  replicas: {{ .Values.events_generator.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: event-generator
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: event-generator
          image: "{{ .Values.tango_example.image.registry }}/{{ .Values.tango_example.image.image }}:{{ .Values.tango_example.image.tag }}"
          imagePullPolicy: {{ .Values.tango_example.image.pullPolicy }}
          command:
            - sh
          args:
            - -c
            - "retry --max=10 -- python3 /app/src/ska_tango_examples/teams/TestDevice.py test"
          env:
          - name: TANGO_HOST
            value: {{ .Values.global.tango_host}}
          - name: DEVICE_NAME
            value: "{{ .Values.events_generator.tangoDeviceName }}"
{{ end }}