{{ if (coalesce .Values.global.minikube .Values.minikube false) }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-generic-pv
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
{{ if or (.Values.global.annotations) (.Values.annotations) }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations) | indent 4 }}
{{ end }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /generic-pv-{{ .Release.Name }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-another-generic-pv
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
{{ if or (.Values.global.annotations) (.Values.annotations) }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations) | indent 4 }}
{{ end }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /another-generic-pv-{{ .Release.Name }}
{{ end }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-generic-pvc
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
{{ if or (.Values.global.annotations) (.Values.annotations) }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations) | indent 4 }}
{{ end }}
spec:
{{ if (coalesce .Values.global.minikube .Values.minikube false)  }}
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
{{ else }}
  storageClassName: nfss1
  accessModes:
    - ReadWriteMany
{{ end }}
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-another-generic-pvc
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml (coalesce .Values.global.labels .Values.labels "label:none") | indent 4 }}
{{ if or (.Values.global.annotations) (.Values.annotations) }}
  annotations:
{{ toYaml (coalesce .Values.global.annotations .Values.annotations) | indent 4 }}
{{ end }}
spec:
{{ if (coalesce .Values.global.minikube .Values.minikube false)  }}
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
{{ else }}
  storageClassName: nfss1
  accessModes:
    - ReadWriteMany
{{ end }}
  resources:
    requests:
      storage: 1Gi
